filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: log
    json.ignore_decoding_error: true
    processors:
      - add_docker_metadata:
          host: 'unix:///var/run/docker.sock'
      - decode_json_fields:
          fields: ['message']
          process_array: false
          max_depth: 1
          target: ''
          overwrite_keys: true
          add_error_key: true
          ignore_failure: true
      # Filtrar logs por tipo de contenedor
      - drop_event:
          when:
            or:
              - contains:
                  container.image.name: 'docker.elastic.co/beats/filebeat'
              - contains:
                  container.labels.com_docker_compose_service: 'filebeat'
              - contains:
                  message: 'Error decoding JSON'

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Desactivar setup automático con Kibana
setup.dashboards.enabled: false
setup.kibana.enabled: false

# Configuración para reportar problemas menos verbosa
logging.level: error

output.logstash:
  hosts: ['logstash:5044']
